export type EvVehicleCategory = "taxi" | "personal" | "scooter";

export type EvVehicle = {
  id: string;
  name: string;
  brand: string;
  category: EvVehicleCategory;
  segment: string;
  icon: "car" | "suv" | "mpv" | "scooter";
  seats?: number;
  rangeKm: number;
  batteryKwh?: number;
  batteryPct: number;
  chargingTimeMin: number;
  dailyEarnings: number;
  monthlyFuelSavings: number;
  emiEstimate: number;
  aiRecommended?: boolean;
  aiBadge?: string;
  bestFor: string;
  nearbyChargingStations: number;
  useCase: string;
  accent: "cyan" | "green" | "saffron" | "violet";
  tags: string[];
};

export type EvSection = {
  id: EvVehicleCategory;
  emoji: string;
  title: string;
  subtitle: string;
  vehicles: EvVehicle[];
};

export const TAXI_FLEET_EVS: EvVehicle[] = [
  {
    id: "vinfast-limo-green",
    name: "Limo Green MPV",
    brand: "VinFast",
    category: "taxi",
    segment: "Premium fleet MPV",
    icon: "mpv",
    seats: 7,
    rangeKm: 517,
    batteryKwh: 60.13,
    batteryPct: 82,
    chargingTimeMin: 38,
    dailyEarnings: 4200,
    monthlyFuelSavings: 14200,
    emiEstimate: 28900,
    aiRecommended: true,
    aiBadge: "Airport fleet pick",
    bestFor: "Airport & premium taxi operators",
    nearbyChargingStations: 14,
    useCase: "Fleet optimized · 7-seater airport rides · premium taxi",
    accent: "cyan",
    tags: ["7 seats", "517 km", "60.13 kWh", "Fleet"],
  },
  {
    id: "vinfast-vf5",
    name: "VF 5",
    brand: "VinFast",
    category: "taxi",
    segment: "Compact urban EV",
    icon: "suv",
    seats: 5,
    rangeKm: 326,
    batteryKwh: 37.23,
    batteryPct: 71,
    chargingTimeMin: 42,
    dailyEarnings: 3100,
    monthlyFuelSavings: 9800,
    emiEstimate: 18900,
    aiBadge: "City share ready",
    bestFor: "Urban ride-sharing & smart taxi",
    nearbyChargingStations: 22,
    useCase: "Connected taxi · city ride-sharing focused",
    accent: "green",
    tags: ["Compact", "Smart connected", "City rides"],
  },
  {
    id: "tata-nexon-ev",
    name: "Nexon EV",
    brand: "Tata",
    category: "taxi",
    segment: "Indian fleet favorite",
    icon: "suv",
    seats: 5,
    rangeKm: 465,
    batteryKwh: 40.5,
    batteryPct: 68,
    chargingTimeMin: 55,
    dailyEarnings: 3400,
    monthlyFuelSavings: 11200,
    emiEstimate: 16800,
    aiRecommended: true,
    aiBadge: "Best ROI India",
    bestFor: "Affordable EV taxi fleets",
    nearbyChargingStations: 31,
    useCase: "Indian fleet favorite · affordable EV taxi",
    accent: "saffron",
    tags: ["465 km", "Affordable", "Fleet proven"],
  },
  {
    id: "mahindra-xuv400",
    name: "XUV400",
    brand: "Mahindra",
    category: "taxi",
    segment: "Long-range driver EV",
    icon: "suv",
    seats: 5,
    rangeKm: 456,
    batteryKwh: 39.4,
    batteryPct: 76,
    chargingTimeMin: 50,
    dailyEarnings: 3850,
    monthlyFuelSavings: 12800,
    emiEstimate: 19500,
    aiBadge: "High mileage",
    bestFor: "Long-shift drivers · high daily earnings",
    nearbyChargingStations: 18,
    useCase: "Long-range driver vehicle · high earning potential",
    accent: "violet",
    tags: ["456 km", "Long range", "High earnings"],
  },
];

export const PERSONAL_EV_OWNERSHIP: EvVehicle[] = [
  {
    id: "vinfast-vf3",
    name: "VF 3",
    brand: "VinFast",
    category: "personal",
    segment: "Micro SUV",
    icon: "suv",
    seats: 4,
    rangeKm: 210,
    batteryKwh: 18.64,
    batteryPct: 88,
    chargingTimeMin: 28,
    dailyEarnings: 1850,
    monthlyFuelSavings: 6200,
    emiEstimate: 12400,
    aiBadge: "Starter EV",
    bestFor: "Beginner gig workers · first EV",
    nearbyChargingStations: 26,
    useCase: "Micro SUV · beginner worker EV",
    accent: "green",
    tags: ["210 km", "Micro SUV", "Beginner"],
  },
  {
    id: "vinfast-vf6",
    name: "VF 6",
    brand: "VinFast",
    category: "personal",
    segment: "Compact SUV",
    icon: "suv",
    seats: 5,
    rangeKm: 468,
    batteryKwh: 59.6,
    batteryPct: 74,
    chargingTimeMin: 36,
    dailyEarnings: 2950,
    monthlyFuelSavings: 10500,
    emiEstimate: 22400,
    aiRecommended: true,
    aiBadge: "Family + gig hybrid",
    bestFor: "Family use + evening gig shifts",
    nearbyChargingStations: 19,
    useCase: "Compact SUV · family + gig work hybrid",
    accent: "cyan",
    tags: ["468 km", "Compact SUV", "Hybrid use"],
  },
  {
    id: "vinfast-vf7",
    name: "VF 7",
    brand: "VinFast",
    category: "personal",
    segment: "Premium ADAS SUV",
    icon: "suv",
    seats: 5,
    rangeKm: 532,
    batteryKwh: 87.7,
    batteryPct: 91,
    chargingTimeMin: 32,
    dailyEarnings: 4500,
    monthlyFuelSavings: 15800,
    emiEstimate: 38900,
    aiBadge: "Executive rides",
    bestFor: "Premium ride category · ADAS drivers",
    nearbyChargingStations: 12,
    useCase: "Premium ADAS SUV · executive ride category",
    accent: "violet",
    tags: ["532 km", "ADAS", "Executive"],
  },
  {
    id: "vinfast-mpv7",
    name: "MPV 7",
    brand: "VinFast",
    category: "personal",
    segment: "Premium 7-seater",
    icon: "mpv",
    seats: 7,
    rangeKm: 468,
    batteryKwh: 59.6,
    batteryPct: 79,
    chargingTimeMin: 40,
    dailyEarnings: 3600,
    monthlyFuelSavings: 13200,
    emiEstimate: 31200,
    aiRecommended: true,
    aiBadge: "Family fleet",
    bestFor: "Large family + fleet leasing",
    nearbyChargingStations: 15,
    useCase: "Premium 7-seater · long-range family/fleet EV",
    accent: "saffron",
    tags: ["7 seats", "468 km", "Premium"],
  },
];

export const GIG_WORKER_SCOOTERS: EvVehicle[] = [
  {
    id: "vinfast-evo",
    name: "Evo",
    brand: "VinFast",
    category: "scooter",
    segment: "Daily city commute",
    icon: "scooter",
    rangeKm: 103,
    batteryKwh: 3.5,
    batteryPct: 92,
    chargingTimeMin: 180,
    dailyEarnings: 980,
    monthlyFuelSavings: 4200,
    emiEstimate: 3200,
    aiRecommended: true,
    aiBadge: "Delivery pick",
    bestFor: "Food & parcel delivery workers",
    nearbyChargingStations: 34,
    useCase: "Daily city commute · delivery optimized",
    accent: "green",
    tags: ["103 km", "Delivery", "Lightweight"],
  },
  {
    id: "vinfast-evo-grand",
    name: "Evo Grand",
    brand: "VinFast",
    category: "scooter",
    segment: "Extended battery",
    icon: "scooter",
    rangeKm: 142,
    batteryKwh: 4.8,
    batteryPct: 85,
    chargingTimeMin: 210,
    dailyEarnings: 1240,
    monthlyFuelSavings: 5100,
    emiEstimate: 4100,
    aiBadge: "Long shift",
    bestFor: "Extended delivery shifts · multi-zone",
    nearbyChargingStations: 28,
    useCase: "Extended battery · long-shift delivery support",
    accent: "cyan",
    tags: ["142 km", "Extended", "Multi-zone"],
  },
  {
    id: "vinfast-feliz",
    name: "Feliz",
    brand: "VinFast",
    category: "scooter",
    segment: "Affordable urban",
    icon: "scooter",
    rangeKm: 98,
    batteryKwh: 3.2,
    batteryPct: 78,
    chargingTimeMin: 165,
    dailyEarnings: 820,
    monthlyFuelSavings: 3800,
    emiEstimate: 2800,
    aiBadge: "Budget friendly",
    bestFor: "Traffic-heavy urban gig routes",
    nearbyChargingStations: 41,
    useCase: "Affordable urban scooter · traffic friendly",
    accent: "saffron",
    tags: ["98 km", "Affordable", "Urban"],
  },
  {
    id: "vinfast-viper",
    name: "Viper",
    brand: "VinFast",
    category: "scooter",
    segment: "Modern performance",
    icon: "scooter",
    rangeKm: 118,
    batteryKwh: 4.1,
    batteryPct: 67,
    chargingTimeMin: 195,
    dailyEarnings: 1100,
    monthlyFuelSavings: 4600,
    emiEstimate: 4800,
    aiBadge: "Youth choice",
    bestFor: "Young gig workers · quick commerce",
    nearbyChargingStations: 22,
    useCase: "Aggressive modern scooter · young gig workers",
    accent: "violet",
    tags: ["118 km", "Sporty", "Quick commerce"],
  },
  {
    id: "vinfast-theon-s",
    name: "Theon S",
    brand: "VinFast",
    category: "scooter",
    segment: "Premium performance",
    icon: "scooter",
    rangeKm: 165,
    batteryKwh: 5.6,
    batteryPct: 94,
    chargingTimeMin: 240,
    dailyEarnings: 1480,
    monthlyFuelSavings: 5800,
    emiEstimate: 6200,
    aiRecommended: true,
    aiBadge: "High-speed delivery",
    bestFor: "Premium delivery · express logistics",
    nearbyChargingStations: 16,
    useCase: "Premium performance · high-speed delivery category",
    accent: "cyan",
    tags: ["165 km", "Premium", "Express"],
  },
];

export const EV_SECTIONS: EvSection[] = [
  {
    id: "taxi",
    emoji: "🚕",
    title: "Taxi Fleet EVs",
    subtitle: "Fleet-grade · airport & ride-share ready",
    vehicles: TAXI_FLEET_EVS,
  },
  {
    id: "personal",
    emoji: "🚗",
    title: "Personal EV Ownership",
    subtitle: "Own your EV · family + gig hybrid",
    vehicles: PERSONAL_EV_OWNERSHIP,
  },
  {
    id: "scooter",
    emoji: "🛵",
    title: "Gig Worker Scooters",
    subtitle: "Last-mile · delivery optimized",
    vehicles: GIG_WORKER_SCOOTERS,
  },
];

export const ALL_EV_VEHICLES = [...TAXI_FLEET_EVS, ...PERSONAL_EV_OWNERSHIP, ...GIG_WORKER_SCOOTERS];

export const DEMO_FLEET_ANALYTICS = {
  totalVehicles: 248,
  activeToday: 186,
  avgSoc: 74,
  efficiencyKmPerKwh: 6.2,
  carbonSavedKg: 4200,
  maintenanceAlerts: 3,
  uptimePct: 99.2,
  revenueToday: 842000,
  revenueGrowthPct: 14.8,
  chargingSessionsToday: 312,
  avgChargeTimeMin: 34,
  fleetUtilizationPct: 78,
  weeklyRevenue: [
    { day: "Mon", revenue: 720000, trips: 1840 },
    { day: "Tue", revenue: 780000, trips: 1920 },
    { day: "Wed", revenue: 810000, trips: 2010 },
    { day: "Thu", revenue: 795000, trips: 1980 },
    { day: "Fri", revenue: 920000, trips: 2240 },
    { day: "Sat", revenue: 980000, trips: 2410 },
    { day: "Sun", revenue: 842000, trips: 2100 },
  ],
  socTrend: [
    { t: "6a", v: 92 },
    { t: "9a", v: 78 },
    { t: "12p", v: 65 },
    { t: "3p", v: 58 },
    { t: "6p", v: 74 },
    { t: "9p", v: 88 },
  ],
};

export const DEMO_CHARGING_HUBS = [
  {
    id: "wf",
    name: "VinFast × GigAI — Whitefield",
    slots: 24,
    available: 18,
    waitMin: 4,
    solar: true,
    powerKw: 150,
    pricePerKwh: 12.5,
    distanceKm: 1.2,
  },
  {
    id: "kor",
    name: "Solar Carport — Koramangala",
    slots: 16,
    available: 9,
    waitMin: 6,
    solar: true,
    powerKw: 120,
    pricePerKwh: 11.8,
    distanceKm: 2.8,
  },
  {
    id: "ecity",
    name: "Worker Housing Yard — E-City",
    slots: 32,
    available: 24,
    waitMin: 3,
    solar: true,
    powerKw: 180,
    pricePerKwh: 10.9,
    distanceKm: 4.1,
  },
  {
    id: "hsr",
    name: "GigAI SuperHub — HSR Layout",
    slots: 40,
    available: 31,
    waitMin: 2,
    solar: false,
    powerKw: 250,
    pricePerKwh: 13.2,
    distanceKm: 3.4,
  },
];

export const DEMO_WORKER_PROFILE = {
  name: "Rajesh K.",
  role: "Taxi + delivery hybrid",
  dailyKm: 142,
  shiftHours: 10,
  currentVehicle: "Petrol auto",
  monthlyFuelSpend: 14800,
  priority: "maximize earnings" as const,
};

export const DEMO_AI_RECOMMENDATIONS = [
  {
    vehicleId: "vinfast-limo-green",
    score: 96,
    reason: "Your airport route pattern + 7-seat demand fits Limo Green MPV",
  },
  {
    vehicleId: "tata-nexon-ev",
    score: 91,
    reason: "Best ROI for Bengaluru taxi fleets with wide charging coverage",
  },
  {
    vehicleId: "vinfast-vf6",
    score: 88,
    reason: "Family + evening gig hybrid with 468 km range",
  },
  {
    vehicleId: "vinfast-evo",
    score: 85,
    reason: "Delivery side-hustle with lowest EMI entry point",
  },
];
