/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as SmartHubRouteImport } from './routes/smart-hub'
import { Route as ShramsetuRouteImport } from './routes/shramsetu'
import { Route as RoiRouteImport } from './routes/roi'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as JoinRouteImport } from './routes/join'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as HiringRouteImport } from './routes/hiring'
import { Route as FutureRouteImport } from './routes/future'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as IndexRouteImport } from './routes/index'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartHubRoute = SmartHubRouteImport.update({
  id: '/smart-hub',
  path: '/smart-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ShramsetuRoute = ShramsetuRouteImport.update({
  id: '/shramsetu',
  path: '/shramsetu',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiRoute = RoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringRoute = HiringRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureRoute = FutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cities': typeof CitiesRoute
  '/future': typeof FutureRoute
  '/hiring': typeof HiringRoute
  '/infrastructure': typeof InfrastructureRoute
  '/join': typeof JoinRoute
  '/manifesto': typeof ManifestoRoute
  '/roi': typeof RoiRoute
  '/shramsetu': typeof ShramsetuRoute
  '/smart-hub': typeof SmartHubRoute
  '/workers': typeof WorkersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cities': typeof CitiesRoute
  '/future': typeof FutureRoute
  '/hiring': typeof HiringRoute
  '/infrastructure': typeof InfrastructureRoute
  '/join': typeof JoinRoute
  '/manifesto': typeof ManifestoRoute
  '/roi': typeof RoiRoute
  '/shramsetu': typeof ShramsetuRoute
  '/smart-hub': typeof SmartHubRoute
  '/workers': typeof WorkersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cities': typeof CitiesRoute
  '/future': typeof FutureRoute
  '/hiring': typeof HiringRoute
  '/infrastructure': typeof InfrastructureRoute
  '/join': typeof JoinRoute
  '/manifesto': typeof ManifestoRoute
  '/roi': typeof RoiRoute
  '/shramsetu': typeof ShramsetuRoute
  '/smart-hub': typeof SmartHubRoute
  '/workers': typeof WorkersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cities'
    | '/future'
    | '/hiring'
    | '/infrastructure'
    | '/join'
    | '/manifesto'
    | '/roi'
    | '/shramsetu'
    | '/smart-hub'
    | '/workers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cities'
    | '/future'
    | '/hiring'
    | '/infrastructure'
    | '/join'
    | '/manifesto'
    | '/roi'
    | '/shramsetu'
    | '/smart-hub'
    | '/workers'
  id:
    | '__root__'
    | '/'
    | '/cities'
    | '/future'
    | '/hiring'
    | '/infrastructure'
    | '/join'
    | '/manifesto'
    | '/roi'
    | '/shramsetu'
    | '/smart-hub'
    | '/workers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitiesRoute: typeof CitiesRoute
  FutureRoute: typeof FutureRoute
  HiringRoute: typeof HiringRoute
  InfrastructureRoute: typeof InfrastructureRoute
  JoinRoute: typeof JoinRoute
  ManifestoRoute: typeof ManifestoRoute
  RoiRoute: typeof RoiRoute
  ShramsetuRoute: typeof ShramsetuRoute
  SmartHubRoute: typeof SmartHubRoute
  WorkersRoute: typeof WorkersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-hub': {
      id: '/smart-hub'
      path: '/smart-hub'
      fullPath: '/smart-hub'
      preLoaderRoute: typeof SmartHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shramsetu': {
      id: '/shramsetu'
      path: '/shramsetu'
      fullPath: '/shramsetu'
      preLoaderRoute: typeof ShramsetuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi': {
      id: '/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof RoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring': {
      id: '/hiring'
      path: '/hiring'
      fullPath: '/hiring'
      preLoaderRoute: typeof HiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future': {
      id: '/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof FutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitiesRoute: CitiesRoute,
  FutureRoute: FutureRoute,
  HiringRoute: HiringRoute,
  InfrastructureRoute: InfrastructureRoute,
  JoinRoute: JoinRoute,
  ManifestoRoute: ManifestoRoute,
  RoiRoute: RoiRoute,
  ShramsetuRoute: ShramsetuRoute,
  SmartHubRoute: SmartHubRoute,
  WorkersRoute: WorkersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
