/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SmartHubRouteImport } from './routes/smart-hub'
import { Route as ShramsetuRouteImport } from './routes/shramsetu'
import { Route as RoiRouteImport } from './routes/roi'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as JoinRouteImport } from './routes/join'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as HiringRouteImport } from './routes/hiring'
import { Route as FutureRouteImport } from './routes/future'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as EvInfrastructureRouteImport } from './routes/ev-infrastructure'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as IndexRouteImport } from './routes/index'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartHubRoute = SmartHubRouteImport.update({
  id: '/smart-hub',
  path: '/smart-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ShramsetuRoute = ShramsetuRouteImport.update({
  id: '/shramsetu',
  path: '/shramsetu',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiRoute = RoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringRoute = HiringRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureRoute = FutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const EvInfrastructureRoute = EvInfrastructureRouteImport.update({
  id: '/ev-infrastructure',
  path: '/ev-infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cities': typeof CitiesRoute
  '/ev-infrastructure': typeof EvInfrastructureRoute
  '/founder': typeof FounderRoute
  '/future': typeof FutureRoute
  '/hiring': typeof HiringRoute
  '/infrastructure': typeof InfrastructureRoute
  '/investors': typeof InvestorsRoute
  '/join': typeof JoinRoute
  '/manifesto': typeof ManifestoRoute
  '/roadmap': typeof RoadmapRoute
  '/roi': typeof RoiRoute
  '/shramsetu': typeof ShramsetuRoute
  '/smart-hub': typeof SmartHubRoute
  '/status': typeof StatusRoute
  '/workers': typeof WorkersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cities': typeof CitiesRoute
  '/ev-infrastructure': typeof EvInfrastructureRoute
  '/founder': typeof FounderRoute
  '/future': typeof FutureRoute
  '/hiring': typeof HiringRoute
  '/infrastructure': typeof InfrastructureRoute
  '/investors': typeof InvestorsRoute
  '/join': typeof JoinRoute
  '/manifesto': typeof ManifestoRoute
  '/roadmap': typeof RoadmapRoute
  '/roi': typeof RoiRoute
  '/shramsetu': typeof ShramsetuRoute
  '/smart-hub': typeof SmartHubRoute
  '/status': typeof StatusRoute
  '/workers': typeof WorkersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cities': typeof CitiesRoute
  '/ev-infrastructure': typeof EvInfrastructureRoute
  '/founder': typeof FounderRoute
  '/future': typeof FutureRoute
  '/hiring': typeof HiringRoute
  '/infrastructure': typeof InfrastructureRoute
  '/investors': typeof InvestorsRoute
  '/join': typeof JoinRoute
  '/manifesto': typeof ManifestoRoute
  '/roadmap': typeof RoadmapRoute
  '/roi': typeof RoiRoute
  '/shramsetu': typeof ShramsetuRoute
  '/smart-hub': typeof SmartHubRoute
  '/status': typeof StatusRoute
  '/workers': typeof WorkersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cities'
    | '/ev-infrastructure'
    | '/founder'
    | '/future'
    | '/hiring'
    | '/infrastructure'
    | '/investors'
    | '/join'
    | '/manifesto'
    | '/roadmap'
    | '/roi'
    | '/shramsetu'
    | '/smart-hub'
    | '/status'
    | '/workers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cities'
    | '/ev-infrastructure'
    | '/founder'
    | '/future'
    | '/hiring'
    | '/infrastructure'
    | '/investors'
    | '/join'
    | '/manifesto'
    | '/roadmap'
    | '/roi'
    | '/shramsetu'
    | '/smart-hub'
    | '/status'
    | '/workers'
  id:
    | '__root__'
    | '/'
    | '/cities'
    | '/ev-infrastructure'
    | '/founder'
    | '/future'
    | '/hiring'
    | '/infrastructure'
    | '/investors'
    | '/join'
    | '/manifesto'
    | '/roadmap'
    | '/roi'
    | '/shramsetu'
    | '/smart-hub'
    | '/status'
    | '/workers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitiesRoute: typeof CitiesRoute
  EvInfrastructureRoute: typeof EvInfrastructureRoute
  FounderRoute: typeof FounderRoute
  FutureRoute: typeof FutureRoute
  HiringRoute: typeof HiringRoute
  InfrastructureRoute: typeof InfrastructureRoute
  InvestorsRoute: typeof InvestorsRoute
  JoinRoute: typeof JoinRoute
  ManifestoRoute: typeof ManifestoRoute
  RoadmapRoute: typeof RoadmapRoute
  RoiRoute: typeof RoiRoute
  ShramsetuRoute: typeof ShramsetuRoute
  SmartHubRoute: typeof SmartHubRoute
  StatusRoute: typeof StatusRoute
  WorkersRoute: typeof WorkersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-hub': {
      id: '/smart-hub'
      path: '/smart-hub'
      fullPath: '/smart-hub'
      preLoaderRoute: typeof SmartHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shramsetu': {
      id: '/shramsetu'
      path: '/shramsetu'
      fullPath: '/shramsetu'
      preLoaderRoute: typeof ShramsetuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi': {
      id: '/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof RoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring': {
      id: '/hiring'
      path: '/hiring'
      fullPath: '/hiring'
      preLoaderRoute: typeof HiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future': {
      id: '/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof FutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ev-infrastructure': {
      id: '/ev-infrastructure'
      path: '/ev-infrastructure'
      fullPath: '/ev-infrastructure'
      preLoaderRoute: typeof EvInfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitiesRoute: CitiesRoute,
  EvInfrastructureRoute: EvInfrastructureRoute,
  FounderRoute: FounderRoute,
  FutureRoute: FutureRoute,
  HiringRoute: HiringRoute,
  InfrastructureRoute: InfrastructureRoute,
  InvestorsRoute: InvestorsRoute,
  JoinRoute: JoinRoute,
  ManifestoRoute: ManifestoRoute,
  RoadmapRoute: RoadmapRoute,
  RoiRoute: RoiRoute,
  ShramsetuRoute: ShramsetuRoute,
  SmartHubRoute: SmartHubRoute,
  StatusRoute: StatusRoute,
  WorkersRoute: WorkersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
